In [1]:
import requests

In [6]:
!pip install selenium webdriver-manager

Requirement already satisfied: selenium in c:\codes\mywebapp\venv\lib\site-packages (4.39.0)
Requirement already satisfied: webdriver-manager in c:\codes\mywebapp\venv\lib\site-packages (4.0.2)
Requirement already satisfied: urllib3[socks]<3.0,>=2.5.0 in c:\codes\mywebapp\venv\lib\site-packages (from selenium) (2.6.2)
Requirement already satisfied: trio<1.0,>=0.31.0 in c:\codes\mywebapp\venv\lib\site-packages (from selenium) (0.32.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in c:\codes\mywebapp\venv\lib\site-packages (from selenium) (0.12.2)
Requirement already satisfied: certifi>=2025.10.5 in c:\codes\mywebapp\venv\lib\site-packages (from selenium) (2025.11.12)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in c:\codes\mywebapp\venv\lib\site-packages (from selenium) (4.15.0)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in c:\codes\mywebapp\venv\lib\site-packages (from selenium) (1.9.0)
Requirement already satisfied: requests in c:\codes\mywebapp\venv\lib\site-packages (from webdriver-manager) (2.32.3)
Requirement already satisfied: python-dotenv in c:\codes\mywebapp\venv\lib\site-packages (from webdriver-manager) (1.2.1)
Requirement already satisfied: packaging in c:\codes\mywebapp\venv\lib\site-packages (from webdriver-manager) (24.1)
Requirement already satisfied: attrs>=23.2.0 in c:\codes\mywebapp\venv\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (25.4.0)
Requirement already satisfied: sortedcontainers in c:\codes\mywebapp\venv\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in c:\codes\mywebapp\venv\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.10)
Requirement already satisfied: outcome in c:\codes\mywebapp\venv\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\codes\mywebapp\venv\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\codes\mywebapp\venv\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.0.0)
Requirement already satisfied: wsproto>=0.14 in c:\codes\mywebapp\venv\lib\site-packages (from trio-websocket<1.0,>=0.12.2->selenium) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\codes\mywebapp\venv\lib\site-packages (from urllib3[socks]<3.0,>=2.5.0->selenium) (1.7.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\codes\mywebapp\venv\lib\site-packages (from requests->webdriver-manager) (3.3.2)
Requirement already satisfied: pycparser in c:\codes\mywebapp\venv\lib\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium) (2.23)
Requirement already satisfied: h11<1,>=0.16.0 in c:\codes\mywebapp\venv\lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)

[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
!python --version

Python 3.12.3
Collecting selenium
  Obtaining dependency information for selenium from https://files.pythonhosted.org/packages/58/d0/55a6b7c6f35aad4c8a54be0eb7a52c1ff29a59542fc3e655f0ecbb14456d/selenium-4.39.0-py3-none-any.whl.metadata
  Downloading selenium-4.39.0-py3-none-any.whl.metadata (7.5 kB)
Collecting webdriver-manager
  Obtaining dependency information for webdriver-manager from https://files.pythonhosted.org/packages/b5/b5/3bd0b038d80950ec13e6a2c8d03ed8354867dc60064b172f2f4ffac8afbe/webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata
  Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata (12 kB)
Collecting urllib3[socks]<3.0,>=2.5.0 (from selenium)
  Obtaining dependency information for urllib3[socks]<3.0,>=2.5.0 from https://files.pythonhosted.org/packages/6d/b9/4095b668ea3678bf6a0af005527f39de12fb026516fb3df17495a733b7f8/urllib3-2.6.2-py3-none-any.whl.metadata
  Downloading urllib3-2.6.2-py3-none-any.whl.metadata (6.6 kB)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Obtaining dependency information for trio<1.0,>=0.31.0 from https://files.pythonhosted.org/packages/41/bf/945d527ff706233636c73880b22c7c953f3faeb9d6c7e2e85bfbfd0134a0/trio-0.32.0-py3-none-any.whl.metadata
  Downloading trio-0.32.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Obtaining dependency information for trio-websocket<1.0,>=0.12.2 from https://files.pythonhosted.org/packages/c7/19/eb640a397bba49ba49ef9dbe2e7e5c04202ba045b6ce2ec36e9cadc51e04/trio_websocket-0.12.2-py3-none-any.whl.metadata
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Collecting certifi>=2025.10.5 (from selenium)
  Obtaining dependency information for certifi>=2025.10.5 from https://files.pythonhosted.org/packages/70/7d/9bc192684cea499815ff478dfcdc13835ddf401365057044fb721ec6bddb/certifi-2025.11.12-py3-none-any.whl.metadata
  Downloading certifi-2025.11.12-py3-none-any.whl.metadata (2.5 kB)
Collecting typing_extensions<5.0,>=4.15.0 (from selenium)
  Obtaining dependency information for typing_extensions<5.0,>=4.15.0 from https://files.pythonhosted.org/packages/18/67/36e9267722cc04a6b9f15c7f3441c2363321a3ea07da7ae0c0707beb2a9c/typing_extensions-4.15.0-py3-none-any.whl.metadata
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in c:\codes\mywebapp\venv\lib\site-packages (from selenium) (1.9.0)
Requirement already satisfied: requests in c:\codes\mywebapp\venv\lib\site-packages (from webdriver-manager) (2.32.3)
Collecting python-dotenv (from webdriver-manager)
  Obtaining dependency information for python-dotenv from https://files.pythonhosted.org/packages/14/1b/a298b06749107c305e1fe0f814c6c74aea7b2f1e10989cb30f544a1b3253/python_dotenv-1.2.1-py3-none-any.whl.metadata
  Downloading python_dotenv-1.2.1-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: packaging in c:\codes\mywebapp\venv\lib\site-packages (from webdriver-manager) (24.1)
Requirement already satisfied: attrs>=23.2.0 in c:\codes\mywebapp\venv\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (25.4.0)
Collecting sortedcontainers (from trio<1.0,>=0.31.0->selenium)
  Obtaining dependency information for sortedcontainers from https://files.pythonhosted.org/packages/32/46/9cb0e58b2deb7f82b84065f37f3bffeb12413f947f9388e4cac22c4621ce/sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: idna in c:\codes\mywebapp\venv\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.10)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Obtaining dependency information for outcome from https://files.pythonhosted.org/packages/55/8b/5ab7257531a5d830fc8000c476e63c935488d74609b50f9384a643ec0a62/outcome-1.3.0.post0-py2.py3-none-any.whl.metadata
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting sniffio>=1.3.0 (from trio<1.0,>=0.31.0->selenium)
  Obtaining dependency information for sniffio>=1.3.0 from https://files.pythonhosted.org/packages/e9/44/75a9c9421471a6c4805dbf2356f7c181a29c1879239abab1ea2cc8f38b40/sniffio-1.3.1-py3-none-any.whl.metadata
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: cffi>=1.14 in c:\codes\mywebapp\venv\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.0.0)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Obtaining dependency information for wsproto>=0.14 from https://files.pythonhosted.org/packages/a4/f5/10b68b7b1544245097b2a1b8238f66f2fc6dcaeb24ba5d917f52bd2eed4f/wsproto-1.3.2-py3-none-any.whl.metadata
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Collecting pysocks!=1.5.7,<2.0,>=1.5.6 (from urllib3[socks]<3.0,>=2.5.0->selenium)
  Obtaining dependency information for pysocks!=1.5.7,<2.0,>=1.5.6 from https://files.pythonhosted.org/packages/8d/59/b4572118e098ac8e46e399a1dd0f2d85403ce8bbaad9ec79373ed6badaf9/PySocks-1.7.1-py3-none-any.whl.metadata
  Downloading PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\codes\mywebapp\venv\lib\site-packages (from requests->webdriver-manager) (3.3.2)
Requirement already satisfied: pycparser in c:\codes\mywebapp\venv\lib\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium) (2.23)
Requirement already satisfied: h11<1,>=0.16.0 in c:\codes\mywebapp\venv\lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Downloading selenium-4.39.0-py3-none-any.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB 115.5 kB/s eta 0:01:24
   ---------------------------------------- 0.0/9.7 MB 115.5 kB/s eta 0:01:24
   ---------------------------------------- 0.0/9.7 MB 115.5 kB/s eta 0:01:24
   ---------------------------------------- 0.1/9.7 MB 126.1 kB/s eta 0:01:17
   ---------------------------------------- 0.1/9.7 MB 126.1 kB/s eta 0:01:17
   ---------------------------------------- 0.1/9.7 MB 126.1 kB/s eta 0:01:17
   ---------------------------------------- 0.1/9.7 MB 126.1 kB/s eta 0:01:17
   ---------------------------------------- 0.1/9.7 MB 120.7 kB/s eta 0:01:20
   ---------------------------------------- 0.1/9.7 MB 120.7 kB/s eta 0:01:20
   ---------------------------------------- 0.1/9.7 MB 120.7 kB/s eta 0:01:20
   ---------------------------------------- 0.1/9.7 MB 111.5 kB/s eta 0:01:26
   ---------------------------------------- 0.1/9.7 MB 111.5 kB/s eta 0:01:26
   ---------------------------------------- 0.1/9.7 MB 111.5 kB/s eta 0:01:26
   ---------------------------------------- 0.1/9.7 MB 111.5 kB/s eta 0:01:26
   ---------------------------------------- 0.1/9.7 MB 111.5 kB/s eta 0:01:26
   ---------------------------------------- 0.1/9.7 MB 111.5 kB/s eta 0:01:26
   ---------------------------------------- 0.1/9.7 MB 111.5 kB/s eta 0:01:26
   ---------------------------------------- 0.1/9.7 MB 99.3 kB/s eta 0:01:37
   ---------------------------------------- 0.1/9.7 MB 99.3 kB/s eta 0:01:37
   ---------------------------------------- 0.1/9.7 MB 99.3 kB/s eta 0:01:37
   ---------------------------------------- 0.1/9.7 MB 99.3 kB/s eta 0:01:37
    --------------------------------------- 0.1/9.7 MB 91.2 kB/s eta 0:01:45
    --------------------------------------- 0.1/9.7 MB 91.2 kB/s eta 0:01:45
    --------------------------------------- 0.1/9.7 MB 91.2 kB/s eta 0:01:45
    --------------------------------------- 0.1/9.7 MB 91.2 kB/s eta 0:01:45
    --------------------------------------- 0.1/9.7 MB 91.2 kB/s eta 0:01:45
    --------------------------------------- 0.1/9.7 MB 91.2 kB/s eta 0:01:45
    --------------------------------------- 0.1/9.7 MB 91.2 kB/s eta 0:01:45
    --------------------------------------- 0.1/9.7 MB 91.2 kB/s eta 0:01:45
    --------------------------------------- 0.1/9.7 MB 84.4 kB/s eta 0:01:53
    --------------------------------------- 0.1/9.7 MB 84.4 kB/s eta 0:01:53
    --------------------------------------- 0.1/9.7 MB 84.4 kB/s eta 0:01:53
    --------------------------------------- 0.1/9.7 MB 84.4 kB/s eta 0:01:53
    --------------------------------------- 0.1/9.7 MB 84.4 kB/s eta 0:01:53
    --------------------------------------- 0.1/9.7 MB 84.4 kB/s eta 0:01:53
    --------------------------------------- 0.2/9.7 MB 81.9 kB/s eta 0:01:56
    --------------------------------------- 0.2/9.7 MB 81.9 kB/s eta 0:01:56
    --------------------------------------- 0.2/9.7 MB 81.9 kB/s eta 0:01:56
    --------------------------------------- 0.2/9.7 MB 81.9 kB/s eta 0:01:56
    --------------------------------------- 0.2/9.7 MB 81.9 kB/s eta 0:01:56
    --------------------------------------- 0.2/9.7 MB 81.9 kB/s eta 0:01:56
    --------------------------------------- 0.2/9.7 MB 81.9 kB/s eta 0:01:56
    --------------------------------------- 0.2/9.7 MB 74.4 kB/s eta 0:02:08
    --------------------------------------- 0.2/9.7 MB 74.4 kB/s eta 0:02:08
    --------------------------------------- 0.2/9.7 MB 74.4 kB/s eta 0:02:08
    --------------------------------------- 0.2/9.7 MB 74.4 kB/s eta 0:02:08
    --------------------------------------- 0.2/9.7 MB 74.4 kB/s eta 0:02:08
    --------------------------------------- 0.2/9.7 MB 74.4 kB/s eta 0:02:08
    --------------------------------------- 0.2/9.7 MB 74.2 kB/s eta 0:02:08
    --------------------------------------- 0.2/9.7 MB 74.2 kB/s eta 0:02:08
    --------------------------------------- 0.2/9.7 MB 74.2 kB/s eta 0:02:08
    --------------------------------------- 0.2/9.7 MB 74.2 kB/s eta 0:02:08
    --------------------------------------- 0.2/9.7 MB 74.2 kB/s eta 0:02:08
    --------------------------------------- 0.2/9.7 MB 74.2 kB/s eta 0:02:08
    --------------------------------------- 0.2/9.7 MB 74.2 kB/s eta 0:02:08
    --------------------------------------- 0.2/9.7 MB 74.2 kB/s eta 0:02:08
    --------------------------------------- 0.2/9.7 MB 68.0 kB/s eta 0:02:19
    --------------------------------------- 0.2/9.7 MB 68.0 kB/s eta 0:02:19
    --------------------------------------- 0.2/9.7 MB 68.0 kB/s eta 0:02:19
    --------------------------------------- 0.2/9.7 MB 68.0 kB/s eta 0:02:19
    --------------------------------------- 0.2/9.7 MB 68.0 kB/s eta 0:02:19
    --------------------------------------- 0.2/9.7 MB 69.1 kB/s eta 0:02:17
    --------------------------------------- 0.2/9.7 MB 69.1 kB/s eta 0:02:17
    --------------------------------------- 0.2/9.7 MB 69.1 kB/s eta 0:02:17
    --------------------------------------- 0.2/9.7 MB 69.1 kB/s eta 0:02:17
    --------------------------------------- 0.2/9.7 MB 69.1 kB/s eta 0:02:17
    --------------------------------------- 0.2/9.7 MB 69.1 kB/s eta 0:02:17
    --------------------------------------- 0.2/9.7 MB 69.1 kB/s eta 0:02:17
   - -------------------------------------- 0.2/9.7 MB 68.5 kB/s eta 0:02:18
   - -------------------------------------- 0.2/9.7 MB 68.5 kB/s eta 0:02:18
   - -------------------------------------- 0.2/9.7 MB 68.5 kB/s eta 0:02:18
   - -------------------------------------- 0.2/9.7 MB 68.5 kB/s eta 0:02:18
   - -------------------------------------- 0.2/9.7 MB 68.5 kB/s eta 0:02:18
   - -------------------------------------- 0.2/9.7 MB 68.5 kB/s eta 0:02:18
   - -------------------------------------- 0.2/9.7 MB 68.5 kB/s eta 0:02:18
   - -------------------------------------- 0.2/9.7 MB 68.5 kB/s eta 0:02:18
   - -------------------------------------- 0.3/9.7 MB 65.0 kB/s eta 0:02:25
   - -------------------------------------- 0.3/9.7 MB 65.0 kB/s eta 0:02:25
   - -------------------------------------- 0.3/9.7 MB 65.0 kB/s eta 0:02:25
   - -------------------------------------- 0.3/9.7 MB 65.0 kB/s eta 0:02:25
   - -------------------------------------- 0.3/9.7 MB 65.0 kB/s eta 0:02:25
   - -------------------------------------- 0.3/9.7 MB 65.0 kB/s eta 0:02:25
   - -------------------------------------- 0.3/9.7 MB 65.5 kB/s eta 0:02:24
   - -------------------------------------- 0.3/9.7 MB 65.5 kB/s eta 0:02:24
   - -------------------------------------- 0.3/9.7 MB 65.5 kB/s eta 0:02:24
   - -------------------------------------- 0.3/9.7 MB 65.5 kB/s eta 0:02:24
   - -------------------------------------- 0.3/9.7 MB 64.3 kB/s eta 0:02:26
   - -------------------------------------- 0.3/9.7 MB 64.3 kB/s eta 0:02:26
   - -------------------------------------- 0.3/9.7 MB 64.3 kB/s eta 0:02:26
   - -------------------------------------- 0.3/9.7 MB 64.3 kB/s eta 0:02:26
   - -------------------------------------- 0.3/9.7 MB 64.3 kB/s eta 0:02:26
   - -------------------------------------- 0.3/9.7 MB 66.2 kB/s eta 0:02:22
   - -------------------------------------- 0.3/9.7 MB 66.2 kB/s eta 0:02:22
   - -------------------------------------- 0.3/9.7 MB 66.2 kB/s eta 0:02:22
   - -------------------------------------- 0.3/9.7 MB 66.2 kB/s eta 0:02:22
   - -------------------------------------- 0.3/9.7 MB 66.2 kB/s eta 0:02:22
   - -------------------------------------- 0.3/9.7 MB 67.0 kB/s eta 0:02:20
   - -------------------------------------- 0.3/9.7 MB 67.0 kB/s eta 0:02:20
   - -------------------------------------- 0.3/9.7 MB 67.0 kB/s eta 0:02:20
   - -------------------------------------- 0.3/9.7 MB 67.0 kB/s eta 0:02:20
   - -------------------------------------- 0.3/9.7 MB 66.8 kB/s eta 0:02:20
   - -------------------------------------- 0.3/9.7 MB 66.8 kB/s eta 0:02:20
   - -------------------------------------- 0.3/9.7 MB 66.8 kB/s eta 0:02:20
   - -------------------------------------- 0.3/9.7 MB 66.8 kB/s eta 0:02:20
   - -------------------------------------- 0.4/9.7 MB 68.6 kB/s eta 0:02:16
   - -------------------------------------- 0.4/9.7 MB 68.6 kB/s eta 0:02:16
   - -------------------------------------- 0.4/9.7 MB 68.6 kB/s eta 0:02:16
   - -------------------------------------- 0.4/9.7 MB 68.6 kB/s eta 0:02:16
   - -------------------------------------- 0.4/9.7 MB 67.9 kB/s eta 0:02:17
   - -------------------------------------- 0.4/9.7 MB 67.9 kB/s eta 0:02:17
   - -------------------------------------- 0.4/9.7 MB 67.9 kB/s eta 0:02:17
   - -------------------------------------- 0.4/9.7 MB 67.9 kB/s eta 0:02:17
   - -------------------------------------- 0.4/9.7 MB 69.1 kB/s eta 0:02:15
   - -------------------------------------- 0.4/9.7 MB 69.1 kB/s eta 0:02:15
   - -------------------------------------- 0.4/9.7 MB 69.1 kB/s eta 0:02:15
   - -------------------------------------- 0.4/9.7 MB 69.1 kB/s eta 0:02:15
   - -------------------------------------- 0.4/9.7 MB 69.1 kB/s eta 0:02:15
   - -------------------------------------- 0.4/9.7 MB 69.6 kB/s eta 0:02:13
   - -------------------------------------- 0.4/9.7 MB 69.6 kB/s eta 0:02:13
   - -------------------------------------- 0.4/9.7 MB 70.3 kB/s eta 0:02:12
   - -------------------------------------- 0.4/9.7 MB 70.3 kB/s eta 0:02:12
   - -------------------------------------- 0.4/9.7 MB 70.3 kB/s eta 0:02:12
   - -------------------------------------- 0.4/9.7 MB 70.3 kB/s eta 0:02:12
   - -------------------------------------- 0.4/9.7 MB 70.3 kB/s eta 0:02:12
   - -------------------------------------- 0.4/9.7 MB 70.3 kB/s eta 0:02:12
   - -------------------------------------- 0.4/9.7 MB 70.3 kB/s eta 0:02:12
   - -------------------------------------- 0.4/9.7 MB 70.3 kB/s eta 0:02:12
   - -------------------------------------- 0.4/9.7 MB 70.3 kB/s eta 0:02:12
   - -------------------------------------- 0.4/9.7 MB 69.0 kB/s eta 0:02:14
   - -------------------------------------- 0.4/9.7 MB 69.0 kB/s eta 0:02:14
   - -------------------------------------- 0.4/9.7 MB 69.0 kB/s eta 0:02:14
   - -------------------------------------- 0.4/9.7 MB 69.0 kB/s eta 0:02:14
   - -------------------------------------- 0.4/9.7 MB 69.0 kB/s eta 0:02:14
   - -------------------------------------- 0.5/9.7 MB 67.9 kB/s eta 0:02:16
   - -------------------------------------- 0.5/9.7 MB 67.9 kB/s eta 0:02:16
   - -------------------------------------- 0.5/9.7 MB 67.9 kB/s eta 0:02:16
   - -------------------------------------- 0.5/9.7 MB 67.9 kB/s eta 0:02:16
   - -------------------------------------- 0.5/9.7 MB 67.9 kB/s eta 0:02:16
   - -------------------------------------- 0.5/9.7 MB 67.9 kB/s eta 0:02:16
   - -------------------------------------- 0.5/9.7 MB 68.3 kB/s eta 0:02:15
   - -------------------------------------- 0.5/9.7 MB 68.3 kB/s eta 0:02:15
   - -------------------------------------- 0.5/9.7 MB 68.3 kB/s eta 0:02:15
   - -------------------------------------- 0.5/9.7 MB 68.3 kB/s eta 0:02:15
   - -------------------------------------- 0.5/9.7 MB 68.3 kB/s eta 0:02:15
   - -------------------------------------- 0.5/9.7 MB 68.3 kB/s eta 0:02:15
   - -------------------------------------- 0.5/9.7 MB 68.3 kB/s eta 0:02:15
   - -------------------------------------- 0.5/9.7 MB 68.3 kB/s eta 0:02:15
   -- ------------------------------------- 0.5/9.7 MB 67.8 kB/s eta 0:02:16
   -- ------------------------------------- 0.5/9.7 MB 67.8 kB/s eta 0:02:16
   -- ------------------------------------- 0.5/9.7 MB 67.8 kB/s eta 0:02:16
   -- ------------------------------------- 0.5/9.7 MB 67.8 kB/s eta 0:02:16
   -- ------------------------------------- 0.5/9.7 MB 67.8 kB/s eta 0:02:16
   -- ------------------------------------- 0.5/9.7 MB 67.8 kB/s eta 0:02:16
   -- ------------------------------------- 0.5/9.7 MB 67.8 kB/s eta 0:02:16
   -- ------------------------------------- 0.5/9.7 MB 65.9 kB/s eta 0:02:19
   -- ------------------------------------- 0.5/9.7 MB 65.9 kB/s eta 0:02:19
   -- ------------------------------------- 0.5/9.7 MB 65.9 kB/s eta 0:02:19
   -- ------------------------------------- 0.5/9.7 MB 65.9 kB/s eta 0:02:19
   -- ------------------------------------- 0.5/9.7 MB 65.9 kB/s eta 0:02:19
   -- ------------------------------------- 0.5/9.7 MB 65.9 kB/s eta 0:02:19
   -- ------------------------------------- 0.5/9.7 MB 65.9 kB/s eta 0:02:19
   -- ------------------------------------- 0.5/9.7 MB 65.9 kB/s eta 0:02:19
   -- ------------------------------------- 0.5/9.7 MB 65.9 kB/s eta 0:02:19
   -- ------------------------------------- 0.5/9.7 MB 65.9 kB/s eta 0:02:19
   -- ------------------------------------- 0.5/9.7 MB 64.9 kB/s eta 0:02:21
   -- ------------------------------------- 0.5/9.7 MB 64.9 kB/s eta 0:02:21
   -- ------------------------------------- 0.5/9.7 MB 64.9 kB/s eta 0:02:21
   -- ------------------------------------- 0.5/9.7 MB 64.9 kB/s eta 0:02:21
   -- ------------------------------------- 0.5/9.7 MB 64.9 kB/s eta 0:02:21
   -- ------------------------------------- 0.5/9.7 MB 64.9 kB/s eta 0:02:21
   -- ------------------------------------- 0.5/9.7 MB 64.9 kB/s eta 0:02:21
   -- ------------------------------------- 0.5/9.7 MB 64.9 kB/s eta 0:02:21
   -- ------------------------------------- 0.5/9.7 MB 63.1 kB/s eta 0:02:25
   -- ------------------------------------- 0.5/9.7 MB 63.1 kB/s eta 0:02:25
   -- ------------------------------------- 0.5/9.7 MB 63.1 kB/s eta 0:02:25
   -- ------------------------------------- 0.5/9.7 MB 63.1 kB/s eta 0:02:25
   -- ------------------------------------- 0.5/9.7 MB 63.1 kB/s eta 0:02:25
   -- ------------------------------------- 0.5/9.7 MB 63.1 kB/s eta 0:02:25
   -- ------------------------------------- 0.5/9.7 MB 63.1 kB/s eta 0:02:25

[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
import time

In [1]:
def access_jin10_calendar(date_str):
    """
    访问金十数据指定日期的日历页面
    :param date_str: 日期字符串，格式如 "2025-11-24"
    """
    # 1. 配置Chrome浏览器选项
    chrome_options = Options()
    # 可选：添加无头模式（不显示浏览器窗口）
    # chrome_options.add_argument("--headless=new")
    # 可选：禁用图片加载，提升速度
    chrome_options.add_experimental_option("prefs", {"profile.managed_default_content_settings.images": 2})
    # 禁用浏览器提示
    chrome_options.add_argument("--disable-infobars")
    chrome_options.add_argument("--disable-blink-features=AutomationControlled")
    # 设置用户代理（避免被识别为爬虫）
    chrome_options.add_argument(
        "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    )

    # 2. 初始化WebDriver（自动下载匹配的Chrome驱动）
    driver = webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=chrome_options
    )

    try:
        # 3. 访问目标网址
        url = f"https://rili.jin10.com/day/{date_str}"
        driver.get(url)
        
        # 4. 等待页面加载（可选：根据需要调整等待时间）
        driver.implicitly_wait(10)  # 隐式等待10秒
        time.sleep(2)  # 强制等待2秒确保页面完全加载

        # 5. 验证页面是否成功加载（示例：打印页面标题）
        print(f"页面标题: {driver.title}")
        print(f"当前URL: {driver.current_url}")

        # 可选：获取页面源代码
        page_source = driver.page_source
        # 可在这里添加数据提取逻辑（如查找特定元素、文本等）
    except Exception as e:
        print(f"访问出错: {e}")
    finally:
        # 6. 关闭浏览器（如果是无头模式，必须关闭否则进程残留）
        input("按回车键关闭浏览器...")  # 暂停查看结果
        driver.quit()

# 访问2025-11-24的日历页面
RESP = access_jin10_calendar("2025-12-22")

NameError: name 'Options' is not defined

In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service

# 1. 配置无头模式参数
chrome_options = Options()
# chrome_options.add_argument("--headless=new") # 核心：启用新版无头模式（必须）
# chrome_options.add_argument("--disable-gpu") # 必加：禁用GPU（无头模式下避免报错）
# chrome_options.add_experimental_option("prefs", {"profile.managed_default_content_settings.images": 2}) # 可选：禁用图片加载，提升速度
# chrome_options.add_argument("--window-size=1920,1080") # 可选：解决部分页面渲染问题
# chrome_options.add_argument("--disable-blink-features=AutomationControlled") # 可选：禁用浏览器自动化特征检测（防反爬）

# 2. 初始化驱动（两种方式：自动下载/手动指定）
## 方式A：自动下载驱动（推荐，无需手动管理）
from webdriver_manager.chrome import ChromeDriverManager
driver_path = ChromeDriverManager().install()
print(driver_path)

driver = webdriver.Chrome(
    service=Service(driver_path),
    options=chrome_options
)

C:\Users\xuezhihuan\.wdm\drivers\chromedriver\win64\143.0.7499.192\chromedriver-win32/chromedriver.exe

In [2]:
import time
date_str='2026-01-12' # 周一日期

try:
    # 3. 访问目标网址
    url = f"https://rili.jin10.com/day/{date_str}"
    driver.get(url)
    
    # 4. 等待页面加载（可选：根据需要调整等待时间）
    driver.implicitly_wait(10)  # 隐式等待10秒
    time.sleep(2)  # 强制等待2秒确保页面完全加载

    # 5. 验证页面是否成功加载（示例：打印页面标题）
    print(f"页面标题: {driver.title}")
    print(f"当前URL: {driver.current_url}")

    input("请登录后点击回车...")

    # 可在这里添加数据提取逻辑（如查找特定元素、文本等）
except Exception as e:
    print(f"访问出错: {e}")

页面标题: 财经日历-金十数据
当前URL: https://rili.jin10.com/day/2026-01-12

In [3]:
from selenium.webdriver.common.by import By  # 必须导入
from selenium.webdriver.support.ui import WebDriverWait
import time

weekday_btns = driver.find_elements(By.CSS_SELECTOR, "div.jin-layout-content__left > div > div.index-page-header__wrap > div.date-slider__wrapper > div.date-slider > ul > li")
page_sources = [] # 5天的page_source
countdown_text = '' # 多久公布下一跳数据，用于侧面监测切换到新的日期页面了
for i,btn in enumerate(weekday_btns[:5]):
    print(i+1)
    btn.click()
    while True:
        time.sleep(3)
        try:
            new_countdown_text = driver.find_element(By.CSS_SELECTOR, "#jinTable1 > div.jin-table-body__wrapper > div > div > div > div.countdown-line").text
        except:
            new_countdown_text='no data'
        if countdown_text != new_countdown_text:
            page_sources.append(driver.page_source)
            countdown_text = new_countdown_text
            break

1
2
3
4
5

In [4]:
from bs4 import BeautifulSoup

result1 = []
result2 = []
    
for page_source in page_sources:
    soup = BeautifulSoup(page_source)
    date = soup.select_one('div.datepicker-wrapper > div.datepicker-trigger > span').get_text(strip=True)
    
    for row in soup.select("#jinTable1 > div.jin-table-body__wrapper > div > div > div > div.jin-table-row"):
        content = row.get_text(strip=True, separator='|')
        result1.append( f"{date}|{content}")
    
    for row in soup.select("#jinTable2 > div.jin-table-body__wrapper > div > div.jin-table-row__group"):
        content = row.get_text(strip=True, separator='|')
        result2.append( f"{date}|{content}")

In [5]:
# Data [['date', 'time', 'country', 'star', 'time_period', 'name']]
import pandas as pd
new_result1 = []
for r in result1:
    items = r.split('|')
    if len(items)==9:
        if items[-5]!='视频解析':
            items = items[:len(items)-4] + ['视频解析'] + items[-4:]
    if len(items)==10:
        ts = items[1]
    elif len(items)<10:
        items = items[:1] + [ts] + items[1:]
    new_result1.append('|'.join(items))

res_df1 = pd.DataFrame([r.split('|')[:3] for r in new_result1], columns=['date', 'time', 'name'])

fin_data_df = pd.read_excel('C:\codes\mywebapp\sqlite\jin10_financial_data_list.xlsx')
q_data_names = fin_data_df[fin_data_df['is_store']=='Y']['数据类型'].tolist()
def check_name(x):
    for n in q_data_names:
        if n in x:
            return True
    return False
data_df = res_df1[res_df1['name'].apply(lambda x: check_name(x))]
data_df

<>:17: SyntaxWarning: invalid escape sequence '\c'
<>:17: SyntaxWarning: invalid escape sequence '\c'
C:\Users\xuezhihuan\AppData\Local\Temp\ipykernel_20068\2677587423.py:17: SyntaxWarning: invalid escape sequence '\c'
  fin_data_df = pd.read_excel('C:\codes\mywebapp\sqlite\jin10_financial_data_list.xlsx')

          date   time             name
0   2026-01-12  16:00     瑞士12月消费者信心指数
7   2026-01-13  21:30    美国12月未季调CPI年率
8   2026-01-13  21:30    美国12月季调后CPI月率
9   2026-01-13  21:30  美国12月季调后核心CPI月率
10  2026-01-13  21:30  美国12月未季调核心CPI年率
13  2026-01-14  21:30      美国11月零售销售月率
14  2026-01-14  21:30       美国11月PPI年率
15  2026-01-14  21:30       美国11月PPI月率
24  2026-01-15  15:00    英国11月三个月GDP月率
28  2026-01-15  15:45     法国12月CPI月率终值
29  2026-01-15  17:00   德国2025年全年GDP增速
38  2026-01-16  15:00     德国12月CPI月率终值

In [6]:
# Data [['date', 'time', 'country', 'star', 'time_period', 'name']]
data_df['date'] = data_df['date'].apply(lambda x:x.replace('-',''))
def get_country_name(x):
    country_names = ['美国','日本','加拿大','英国','瑞士','中国', '法国', '德国','欧元区','澳大利亚']
    for n in country_names:
        if n in x:
            return n
    return ''
data_df['country'] = data_df['name'].apply(lambda x:get_country_name(x))
def get_time_period(x):
    time_period_names = [ '11月', '12月', '1月','2月','3月','4月','5月', '6月', '7月', '8月', '9月', '10月',
                         '第一季度','第二季度','第三季度','第四季度']
    for n in time_period_names:
        if n in x:
            return n
    return ''
data_df['time_period'] = data_df['name'].apply(lambda x:get_time_period(x))
data_df['star'] = 3

data_df [['date', 'time', 'country', 'star', 'time_period', 'name']]

C:\Users\xuezhihuan\AppData\Local\Temp\ipykernel_20068\4185348985.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df['date'] = data_df['date'].apply(lambda x:x.replace('-',''))
C:\Users\xuezhihuan\AppData\Local\Temp\ipykernel_20068\4185348985.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df['country'] = data_df['name'].apply(lambda x:get_country_name(x))
C:\Users\xuezhihuan\AppData\Local\Temp\ipykernel_20068\4185348985.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df['time_period'] = data_df['name'].apply(lambda x:get_time_period(x))
C:\Users\xuezhihuan\AppData\Local\Temp\ipykernel_20068\4185348985.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df['star'] = 3

        date   time country  star time_period             name
0   20260112  16:00      瑞士     3         12月     瑞士12月消费者信心指数
7   20260113  21:30      美国     3         12月    美国12月未季调CPI年率
8   20260113  21:30      美国     3         12月    美国12月季调后CPI月率
9   20260113  21:30      美国     3         12月  美国12月季调后核心CPI月率
10  20260113  21:30      美国     3         12月  美国12月未季调核心CPI年率
13  20260114  21:30      美国     3         11月      美国11月零售销售月率
14  20260114  21:30      美国     3         11月       美国11月PPI年率
15  20260114  21:30      美国     3         11月       美国11月PPI月率
24  20260115  15:00      英国     3         11月    英国11月三个月GDP月率
28  20260115  15:45      法国     3         12月     法国12月CPI月率终值
29  20260115  17:00      德国     3               德国2025年全年GDP增速
38  20260116  15:00      德国     3         12月     德国12月CPI月率终值

In [7]:
# Event [['date', 'time', 'country', 'star', 'region', 'people', 'event_content']]
event_df = pd.DataFrame([r.split('|')[:4] for r in result2], columns=['date', 'time', 'country', 'event_content'])
event_df['date'] = event_df['date'].apply(lambda x:x.replace('-',''))
event_df['region'] = ''
event_df['people'] = ''
event_df['star'] = 3

event_df[['date', 'time', 'country', 'star', 'region', 'people', 'event_content']]

,date,time,country,star,region,people,event_content
0,20260112,待定,美国,3,,,七国集团(G7)财长会议。
1,20260113,07:00,美国,3,,,FOMC永久票委、纽约联储主席威廉姆斯发表讲话。
2,20260114,01:00,美国,3,,,EIA公布月度短期能源展望报告。
3,20260114,22:50,美国,3,,,2026年FOMC票委、费城联储主席保尔森就经济前景发表讲话。
4,20260114,23:00,希腊,3,,,美联储理事米兰在雅典发表讲话。
5,20260114,待定,奥地利,3,,,欧佩克公布月度原油市场报告（月报具体公布时间待定，一般于北京时间18-21点左右公布）。
6,20260115,01:00,美国,3,,,2026年FOMC票委、明尼阿波利斯联储主席卡什卡利发表讲话。
7,20260115,03:00,美联储,3,,,美联储公布经济状况褐皮书。
8,20260115,03:10,美国,3,,,FOMC永久票委、纽约联储主席威廉姆斯在一场活动上致开幕词。

In [59]:
!jupyter kernelspec list

Available kernels:
  .venv      C:\Users\xuezhihuan\AppData\Roaming\jupyter\kernels\.venv
  myenv      C:\Users\xuezhihuan\AppData\Roaming\jupyter\kernels\myenv
  python3    C:\Users\xuezhihuan\anaconda3\share\jupyter\kernels\python3

0.01s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.

In [8]:
import pandas as pd
from openpyxl import load_workbook

def overwrite_excel_sheet(df, excel_path, sheet_name):
    """
    覆盖写入 Excel 文件的特定工作表

    Parameters:
    df: 要写入的 DataFrame
    excel_path: Excel 文件路径
    sheet_name: 要覆盖的工作表名称
    """
    # 读取现有 Excel 文件的所有工作表
    with pd.ExcelFile(excel_path) as xls:
        sheet_names = xls.sheet_names

    # 创建 ExcelWriter，模式为 'a'（追加/修改）
    with pd.ExcelWriter(excel_path, engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
        # 如果工作表已存在，会被覆盖
        # 如果工作表不存在，会被创建
        df.to_excel(writer, sheet_name=sheet_name, index=False)

    print(f"已成功将 DataFrame 写入到 {sheet_name} 工作表")

In [9]:
# 使用示例
df = data_df [['date', 'time', 'country', 'star', 'time_period', 'name']]
file_path = r"C:\codes\mywebapp\backend\static\crawl\cloudhands_weely_report\2026-1-12\future_data_event.xlsx"
overwrite_excel_sheet(df, file_path, 'DATA')

已成功将 DataFrame 写入到 DATA 工作表

In [10]:
# 使用示例
df = event_df[['date', 'time', 'country', 'star', 'region', 'people', 'event_content']]
file_path = r"C:\codes\mywebapp\backend\static\crawl\cloudhands_weely_report\2026-1-12\future_data_event.xlsx"
overwrite_excel_sheet(df, file_path, 'EVENT')

已成功将 DataFrame 写入到 EVENT 工作表